#!/usr/bin/env bash
# Opens or updates the ghostty-wasm-update pull request. Never pushes to
# main. Skips the refresh when someone pushed commits to the branch.
#
# Env: GHOSTTY_NEW (commit), STATUS (pass|fail), CATEGORY (failure
# category), GH_TOKEN. Runs on a checkout of main with the new module files
# in the working tree; the "before" values come from HEAD. Reads
# bench-old.txt, bench-new.txt and test-output.txt from the working
# directory when present.
set -euo pipefail

branch="ghostty-wasm-update"
label="ghostty-wasm-failing"
title="Update libghostty-vt to ${GHOSTTY_NEW:0:12}"
dir="vt/internal/ghostty/internal/wasmvt"
wasm="$dir/ghostty-vt.wasm"
gen="$dir/ghostty_vt.go"
ghostty_old="$(git show "HEAD:$dir/GHOSTTY_COMMIT" | sed -n 's/^commit=//p')"
size_old="$(git cat-file -s "HEAD:$wasm")"
gen_size_old="$(git cat-file -s "HEAD:$gen")"
size_new="$(stat -c %s "$wasm")"
gen_size_new="$(stat -c %s "$gen")"

bot="github-actions[bot]"

open_pr() {
  gh pr list --head "$branch" --state open --json number --jq '.[0].number // empty'
}

# The refresh rebuilds the branch from main and force-pushes it. People fix
# abi.go or goldens on this branch (see vt/internal/ghostty/README.md), and
# a forced push would drop their commits, so leave such a branch alone.
if git ls-remote --exit-code --heads origin "refs/heads/$branch" >/dev/null; then
  git fetch --quiet origin "+refs/heads/main:refs/remotes/origin/main" \
    "+refs/heads/$branch:refs/remotes/origin/$branch"
  human="$(git log --format='%an%x09%h %s' "origin/main..origin/$branch" | awk -F '\t' -v bot="$bot" '$1 != bot')"
  if [ -n "$human" ]; then
    notice="Skipped the automated refresh to ${GHOSTTY_NEW} (status: ${STATUS}${CATEGORY:+, ${CATEGORY}}) because \`${branch}\` has commits not made by ${bot}, which a forced push would drop. Merge or close the PR and delete the branch to resume refreshes."
    echo "::warning::${notice}"
    printf '%s\n' "$human"
    number="$(open_pr)"
    if [ -n "$number" ]; then
      gh pr comment "$number" --body "${notice}"
    fi
    exit 0
  fi
else
  # 2 means no such branch; anything else is a failed lookup.
  code=$?
  [ "$code" = "2" ] || exit "$code"
fi

git config user.name "$bot"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$branch"
git add "$wasm" "$gen" "$dir/GHOSTTY_COMMIT"
# A failed build changes nothing; the PR still carries the failure report.
git commit --allow-empty -m "$title"
git push --force origin "$branch"

body="$(mktemp)"
{
  echo "Upstream: https://github.com/ghostty-org/ghostty/compare/${ghostty_old}...${GHOSTTY_NEW}"
  echo
  echo "| | before | after |"
  echo "|---|---|---|"
  echo "| \`.wasm\` size | ${size_old} | ${size_new} |"
  echo "| \`ghostty_vt.go\` size | ${gen_size_old} | ${gen_size_new} |"
  echo
  echo "## BenchmarkVTWrite"
  echo '```'
  echo "before:"; cat bench-old.txt 2>/dev/null || echo "(none)"
  echo "after:"; cat bench-new.txt 2>/dev/null || echo "(none)"
  echo '```'
  if [ "$STATUS" = "fail" ]; then
    echo
    echo "## Failing: ${CATEGORY}"
    echo '```'
    tail -c 60000 test-output.txt 2>/dev/null || true
    echo '```'
  fi
  echo
  echo "Opened by the ghostty-wasm workflow. See vt/internal/ghostty/README.md for what each failure category means."
  echo "\`ghostty_vt.go\` is generated by wasm2go: review the upstream range and the test results, not its diff."
  echo "PRs opened by this workflow don't trigger build.yml: close and reopen to run CI."
} > "$body"

number="$(open_pr)"
if [ -z "$number" ]; then
  draft=()
  [ "$STATUS" = "fail" ] && draft=(--draft)
  gh pr create --base main --head "$branch" --title "$title" --body-file "$body" "${draft[@]}"
  number="$(gh pr list --head "$branch" --state open --json number --jq '.[0].number')"
else
  gh pr edit "$number" --title "$title" --body-file "$body"
fi

if [ "$STATUS" = "fail" ]; then
  gh label create "$label" --color B60205 --force
  gh pr edit "$number" --add-label "$label"
  gh pr ready "$number" --undo || true
else
  gh pr edit "$number" --remove-label "$label" || true
  gh pr ready "$number" || true
fi
